export const changeInputValue = 'changeInputValue'
export const addItem = 'addItem'
export const deleteItem = 'deleteItem'
export const getinitlist = 'getinitlist'
export const initAxiosObj = 'initAxiosObj'